# -*- coding: utf-8 -*-
"""Spearman correlation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ywabB2U8lQx9UeMUzqLbKHETVopksGwc
"""

from google.colab import drive
drive.mount('/content/drive')


import io
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import scipy.stats as stats
import statsmodels.api as sm
import statsmodels.formula.api as smf
from google.colab import files
def Quickdownl(filename):
  plt.savefig(filename)
  files.download(filename)
  return None

# Load the data
df = pd.read_excel('/content/drive/MyDrive/Trinity papers/Jorge chronic pain/Pyhton data/MMN P300.xlsx')

df

df['Pain MMN']  = df['MMN chronic'].rank(method='max')
df['Controls MMN']  = df['MMN controls'].rank(method='max')

df['Pain P300']  = df['P300 chronic'].rank(method='max')
df['Controls P300']  = df['p300 controls'].rank(method='max')

plt.figure(figsize=(5, 5),dpi=900)
sns.set_style("white")
sns.regplot(data = df, x = 'Pain P300',
              y = 'Pain MMN', ci = 95,
              line_kws={"color": "purple", "alpha":0.7, "lw":5},scatter=False,label='CP rho = -0.41, p = .04*')
plt.legend(loc='center left',bbox_to_anchor=(0.15, 1.1))

ax = sns.scatterplot(data=df, x = 'Pain P300',
              y = 'Pain MMN',hue='Pain MMN',palette=['purple'],legend=False)

sns.regplot(data = df, x = 'Controls P300',
              y = 'Controls MMN', ci = 95,
              line_kws={"color": "green", "alpha":0.7, "lw":5},scatter=False,label='HC rho = -0.08, p= 0.6')
plt.legend(loc='center left',bbox_to_anchor=(0.15, 1.1))

ax = sns.scatterplot(data=df, x = 'Controls P300',
              y = 'Controls MMN',hue='Controls MMN',palette=['green'],legend=False)



plt.yticks(fontsize=14)
plt.xticks(fontsize=14)
plt.xlabel('Att ERP',size = 16)
plt.ylabel('Pre-Att ERP',size = 16)
ax.spines['right'].set_visible(False)
ax.spines['top'].set_visible(False)
plt.tight_layout()

# Download
filename = 'Pre-att att ERP correlation.jpg'
Quickdownl(filename)